<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Week 4 - Home | Theory Construction and Statistical Modeling</title>
  <meta name="description" content="This is a guide for the elective course TCSM." />
  <meta name="generator" content="bookdown 0.12 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Week 4 - Home | Theory Construction and Statistical Modeling" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a guide for the elective course TCSM." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Week 4 - Home | Theory Construction and Statistical Modeling" />
  
  <meta name="twitter:description" content="This is a guide for the elective course TCSM." />
  

<meta name="author" content="Caspar J. van Lissa¹" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="week-3-class.html">
<link rel="next" href="week-4-home-1.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="font-awesome.min.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./index.html">TCSM</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course</a></li>
<li class="chapter" data-level="1" data-path="preparing-for-the-course.html"><a href="preparing-for-the-course.html"><i class="fa fa-check"></i><b>1</b> Preparing for the course</a><ul>
<li class="chapter" data-level="1.1" data-path="installing-software.html"><a href="installing-software.html"><i class="fa fa-check"></i><b>1.1</b> Installing software</a><ul>
<li class="chapter" data-level="1.1.1" data-path="installing-software.html"><a href="installing-software.html#installing-r"><i class="fa fa-check"></i><b>1.1.1</b> 1. Installing R</a></li>
<li class="chapter" data-level="1.1.2" data-path="installing-software.html"><a href="installing-software.html#installing-rstudio"><i class="fa fa-check"></i><b>1.1.2</b> 2. Installing RStudio</a></li>
<li class="chapter" data-level="1.1.3" data-path="installing-software.html"><a href="installing-software.html#installing-packages"><i class="fa fa-check"></i><b>1.1.3</b> 3. Installing packages</a></li>
<li class="chapter" data-level="1.1.4" data-path="installing-software.html"><a href="installing-software.html#get-started"><i class="fa fa-check"></i><b>1.1.4</b> Get started</a></li>
<li class="chapter" data-level="1.1.5" data-path="installing-software.html"><a href="installing-software.html#starting-a-new-project-in-rstudio"><i class="fa fa-check"></i><b>1.1.5</b> Starting a new project in Rstudio</a></li>
<li class="chapter" data-level="1.1.6" data-path="installing-software.html"><a href="installing-software.html#code-conventions"><i class="fa fa-check"></i><b>1.1.6</b> Code conventions</a></li>
<li class="chapter" data-level="1.1.7" data-path="installing-software.html"><a href="installing-software.html#getting-help"><i class="fa fa-check"></i><b>1.1.7</b> Getting Help</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-your-data-into-r.html"><a href="getting-your-data-into-r.html"><i class="fa fa-check"></i><b>2</b> Getting your data into R</a><ul>
<li class="chapter" data-level="2.1" data-path="using-r-projects.html"><a href="using-r-projects.html"><i class="fa fa-check"></i><b>2.1</b> Using R projects</a></li>
<li class="chapter" data-level="2.2" data-path="importing-excel-files.html"><a href="importing-excel-files.html"><i class="fa fa-check"></i><b>2.2</b> Importing Excel Files</a><ul>
<li class="chapter" data-level="2.2.1" data-path="importing-excel-files.html"><a href="importing-excel-files.html#inspect-the-data"><i class="fa fa-check"></i><b>2.2.1</b> Inspect the data</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="importing-spss-files.html"><a href="importing-spss-files.html"><i class="fa fa-check"></i><b>2.3</b> Importing SPSS Files</a></li>
<li class="chapter" data-level="2.4" data-path="data-manipulation-optional.html"><a href="data-manipulation-optional.html"><i class="fa fa-check"></i><b>2.4</b> Data manipulation (optional)</a><ul>
<li class="chapter" data-level="2.4.1" data-path="data-manipulation-optional.html"><a href="data-manipulation-optional.html#convertfactors"><i class="fa fa-check"></i><b>2.4.1</b> Converting to factors</a></li>
<li class="chapter" data-level="2.4.2" data-path="data-manipulation-optional.html"><a href="data-manipulation-optional.html#select"><i class="fa fa-check"></i><b>2.4.2</b> Selecting specific cases</a></li>
<li class="chapter" data-level="2.4.3" data-path="data-manipulation-optional.html"><a href="data-manipulation-optional.html#changing-cell-values"><i class="fa fa-check"></i><b>2.4.3</b> Changing cell values</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-1-home.html"><a href="week-1-home.html"><i class="fa fa-check"></i><b>3</b> Week 1 - Home</a><ul>
<li class="chapter" data-level="3.0.1" data-path="week-1-home.html"><a href="week-1-home.html#question-1.a"><i class="fa fa-check"></i><b>3.0.1</b> Question 1.a</a></li>
<li class="chapter" data-level="3.0.2" data-path="week-1-home.html"><a href="week-1-home.html#question-1.b"><i class="fa fa-check"></i><b>3.0.2</b> Question 1.b</a></li>
<li class="chapter" data-level="3.0.3" data-path="week-1-home.html"><a href="week-1-home.html#question-1.c."><i class="fa fa-check"></i><b>3.0.3</b> Question 1.c.</a></li>
<li class="chapter" data-level="3.0.4" data-path="week-1-home.html"><a href="week-1-home.html#question-1.d."><i class="fa fa-check"></i><b>3.0.4</b> Question 1.d.</a></li>
<li class="chapter" data-level="3.0.5" data-path="week-1-home.html"><a href="week-1-home.html#question-1.e."><i class="fa fa-check"></i><b>3.0.5</b> Question 1.e.</a></li>
<li class="chapter" data-level="3.0.6" data-path="week-1-home.html"><a href="week-1-home.html#question-1.f."><i class="fa fa-check"></i><b>3.0.6</b> Question 1.f.</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-1-class.html"><a href="week-1-class.html"><i class="fa fa-check"></i><b>4</b> Week 1 - Class</a><ul>
<li class="chapter" data-level="4.1" data-path="loading-data.html"><a href="loading-data.html"><i class="fa fa-check"></i><b>4.1</b> Loading data</a></li>
<li class="chapter" data-level="4.2" data-path="section-1.html"><a href="section-1.html"><i class="fa fa-check"></i><b>4.2</b> Section 1</a><ul>
<li class="chapter" data-level="4.2.1" data-path="section-1.html"><a href="section-1.html#question-1.a-1"><i class="fa fa-check"></i><b>4.2.1</b> Question 1.a</a></li>
<li class="chapter" data-level="4.2.2" data-path="section-1.html"><a href="section-1.html#question-1.b-1"><i class="fa fa-check"></i><b>4.2.2</b> Question 1.b</a></li>
<li class="chapter" data-level="4.2.3" data-path="section-1.html"><a href="section-1.html#question-1.c"><i class="fa fa-check"></i><b>4.2.3</b> Question 1.c</a></li>
<li class="chapter" data-level="4.2.4" data-path="section-1.html"><a href="section-1.html#question-1.d"><i class="fa fa-check"></i><b>4.2.4</b> Question 1.d</a></li>
<li class="chapter" data-level="4.2.5" data-path="section-1.html"><a href="section-1.html#question-1.e"><i class="fa fa-check"></i><b>4.2.5</b> Question 1.e</a></li>
<li class="chapter" data-level="4.2.6" data-path="section-1.html"><a href="section-1.html#question-1.f"><i class="fa fa-check"></i><b>4.2.6</b> Question 1.f</a></li>
<li class="chapter" data-level="4.2.7" data-path="section-1.html"><a href="section-1.html#question-1.g"><i class="fa fa-check"></i><b>4.2.7</b> Question 1.g</a></li>
<li class="chapter" data-level="4.2.8" data-path="section-1.html"><a href="section-1.html#question-1.h"><i class="fa fa-check"></i><b>4.2.8</b> Question 1.h</a></li>
<li class="chapter" data-level="4.2.9" data-path="section-1.html"><a href="section-1.html#question-1.i"><i class="fa fa-check"></i><b>4.2.9</b> Question 1.i</a></li>
<li class="chapter" data-level="4.2.10" data-path="section-1.html"><a href="section-1.html#question-1.j"><i class="fa fa-check"></i><b>4.2.10</b> Question 1.j</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="section-2.html"><a href="section-2.html"><i class="fa fa-check"></i><b>4.3</b> Section 2</a><ul>
<li class="chapter" data-level="4.3.1" data-path="section-2.html"><a href="section-2.html#research-question-1-anova-does-talking-on-the-phone-interfere-with-peoples-driving-skills"><i class="fa fa-check"></i><b>4.3.1</b> Research question 1 (ANOVA): Does talking on the phone interfere with people’s driving skills?</a></li>
<li class="chapter" data-level="4.3.2" data-path="section-2.html"><a href="section-2.html#question-2.a"><i class="fa fa-check"></i><b>4.3.2</b> Question 2.a</a></li>
<li class="chapter" data-level="4.3.3" data-path="section-2.html"><a href="section-2.html#question-2.b"><i class="fa fa-check"></i><b>4.3.3</b> Question 2.b</a></li>
<li class="chapter" data-level="4.3.4" data-path="section-2.html"><a href="section-2.html#question-2.c"><i class="fa fa-check"></i><b>4.3.4</b> Question 2.c</a></li>
<li class="chapter" data-level="4.3.5" data-path="section-2.html"><a href="section-2.html#question-2.d"><i class="fa fa-check"></i><b>4.3.5</b> Question 2.d</a></li>
<li class="chapter" data-level="4.3.6" data-path="section-2.html"><a href="section-2.html#question-2.e"><i class="fa fa-check"></i><b>4.3.6</b> Question 2.e</a></li>
<li class="chapter" data-level="4.3.7" data-path="section-2.html"><a href="section-2.html#research-question-2-ancova-are-there-differences-in-reaction-time-between-the-conditions-when-controlling-for-age"><i class="fa fa-check"></i><b>4.3.7</b> Research question 2 (ANCOVA): Are there differences in reaction time between the conditions when controlling for age?</a></li>
<li class="chapter" data-level="4.3.8" data-path="section-2.html"><a href="section-2.html#question-2.f"><i class="fa fa-check"></i><b>4.3.8</b> Question 2.f</a></li>
<li class="chapter" data-level="4.3.9" data-path="section-2.html"><a href="section-2.html#question-2.g"><i class="fa fa-check"></i><b>4.3.9</b> Question 2.g</a></li>
<li class="chapter" data-level="4.3.10" data-path="section-2.html"><a href="section-2.html#question-2.h"><i class="fa fa-check"></i><b>4.3.10</b> Question 2.h</a></li>
<li class="chapter" data-level="4.3.11" data-path="section-2.html"><a href="section-2.html#question-2.i"><i class="fa fa-check"></i><b>4.3.11</b> Question 2.i</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="section-3.html"><a href="section-3.html"><i class="fa fa-check"></i><b>4.4</b> Section 3</a><ul>
<li class="chapter" data-level="4.4.1" data-path="section-3.html"><a href="section-3.html#question-3.a"><i class="fa fa-check"></i><b>4.4.1</b> Question 3.a</a></li>
<li class="chapter" data-level="4.4.2" data-path="section-3.html"><a href="section-3.html#question-3.b"><i class="fa fa-check"></i><b>4.4.2</b> Question 3.b</a></li>
<li class="chapter" data-level="4.4.3" data-path="section-3.html"><a href="section-3.html#question-3.c"><i class="fa fa-check"></i><b>4.4.3</b> Question 3.c</a></li>
<li class="chapter" data-level="4.4.4" data-path="section-3.html"><a href="section-3.html#question-3.d"><i class="fa fa-check"></i><b>4.4.4</b> Question 3.d</a></li>
<li class="chapter" data-level="4.4.5" data-path="section-3.html"><a href="section-3.html#question-3.e"><i class="fa fa-check"></i><b>4.4.5</b> Question 3.e</a></li>
<li class="chapter" data-level="4.4.6" data-path="section-3.html"><a href="section-3.html#question-3.f"><i class="fa fa-check"></i><b>4.4.6</b> Question 3.f</a></li>
<li class="chapter" data-level="4.4.7" data-path="section-3.html"><a href="section-3.html#question-3.g"><i class="fa fa-check"></i><b>4.4.7</b> Question 3.g</a></li>
<li class="chapter" data-level="4.4.8" data-path="section-3.html"><a href="section-3.html#question-3.h"><i class="fa fa-check"></i><b>4.4.8</b> Question 3.h</a></li>
<li class="chapter" data-level="4.4.9" data-path="section-3.html"><a href="section-3.html#question-3.i"><i class="fa fa-check"></i><b>4.4.9</b> Question 3.i</a></li>
<li class="chapter" data-level="4.4.10" data-path="section-3.html"><a href="section-3.html#question-3.j"><i class="fa fa-check"></i><b>4.4.10</b> Question 3.j</a></li>
<li class="chapter" data-level="4.4.11" data-path="section-3.html"><a href="section-3.html#question-3.k"><i class="fa fa-check"></i><b>4.4.11</b> Question 3.k</a></li>
<li class="chapter" data-level="4.4.12" data-path="section-3.html"><a href="section-3.html#question-3.l"><i class="fa fa-check"></i><b>4.4.12</b> Question 3.l</a></li>
<li class="chapter" data-level="4.4.13" data-path="section-3.html"><a href="section-3.html#question-3.m"><i class="fa fa-check"></i><b>4.4.13</b> Question 3.m</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-2-home.html"><a href="week-2-home.html"><i class="fa fa-check"></i><b>5</b> Week 2 - Home</a><ul>
<li class="chapter" data-level="5.0.1" data-path="week-2-home.html"><a href="week-2-home.html#question-1.a-2"><i class="fa fa-check"></i><b>5.0.1</b> Question 1.a</a></li>
<li class="chapter" data-level="5.0.2" data-path="week-2-home.html"><a href="week-2-home.html#question-1.b-2"><i class="fa fa-check"></i><b>5.0.2</b> Question 1.b</a></li>
<li class="chapter" data-level="5.0.3" data-path="week-2-home.html"><a href="week-2-home.html#question-1.c-1"><i class="fa fa-check"></i><b>5.0.3</b> Question 1.c</a></li>
<li class="chapter" data-level="5.0.4" data-path="week-2-home.html"><a href="week-2-home.html#question-1.d-1"><i class="fa fa-check"></i><b>5.0.4</b> Question 1.d</a></li>
<li class="chapter" data-level="5.0.5" data-path="week-2-home.html"><a href="week-2-home.html#question-1.e-1"><i class="fa fa-check"></i><b>5.0.5</b> Question 1.e</a></li>
<li class="chapter" data-level="5.0.6" data-path="week-2-home.html"><a href="week-2-home.html#question-1.f-1"><i class="fa fa-check"></i><b>5.0.6</b> Question 1.f</a></li>
<li class="chapter" data-level="5.0.7" data-path="week-2-home.html"><a href="week-2-home.html#question-1.g-1"><i class="fa fa-check"></i><b>5.0.7</b> Question 1.g</a></li>
<li class="chapter" data-level="5.0.8" data-path="week-2-home.html"><a href="week-2-home.html#question-1.h-1"><i class="fa fa-check"></i><b>5.0.8</b> Question 1.h</a></li>
<li class="chapter" data-level="5.0.9" data-path="week-2-home.html"><a href="week-2-home.html#question-1.i-1"><i class="fa fa-check"></i><b>5.0.9</b> Question 1.i</a></li>
<li class="chapter" data-level="5.0.10" data-path="week-2-home.html"><a href="week-2-home.html#question-1.j-1"><i class="fa fa-check"></i><b>5.0.10</b> Question 1.j</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-2-class.html"><a href="week-2-class.html"><i class="fa fa-check"></i><b>6</b> Week 2 - Class</a><ul>
<li class="chapter" data-level="6.1" data-path="loading-data-1.html"><a href="loading-data-1.html"><i class="fa fa-check"></i><b>6.1</b> Loading data</a><ul>
<li class="chapter" data-level="6.1.1" data-path="loading-data-1.html"><a href="loading-data-1.html#question-1"><i class="fa fa-check"></i><b>6.1.1</b> Question 1</a></li>
<li class="chapter" data-level="6.1.2" data-path="loading-data-1.html"><a href="loading-data-1.html#question-2"><i class="fa fa-check"></i><b>6.1.2</b> Question 2</a></li>
<li class="chapter" data-level="6.1.3" data-path="loading-data-1.html"><a href="loading-data-1.html#question-3"><i class="fa fa-check"></i><b>6.1.3</b> Question 3</a></li>
<li class="chapter" data-level="6.1.4" data-path="loading-data-1.html"><a href="loading-data-1.html#question-4"><i class="fa fa-check"></i><b>6.1.4</b> Question 4</a></li>
<li class="chapter" data-level="6.1.5" data-path="loading-data-1.html"><a href="loading-data-1.html#question-5"><i class="fa fa-check"></i><b>6.1.5</b> Question 5</a></li>
<li class="chapter" data-level="6.1.6" data-path="loading-data-1.html"><a href="loading-data-1.html#question-6"><i class="fa fa-check"></i><b>6.1.6</b> Question 6</a></li>
<li class="chapter" data-level="6.1.7" data-path="loading-data-1.html"><a href="loading-data-1.html#question-7"><i class="fa fa-check"></i><b>6.1.7</b> Question 7</a></li>
<li class="chapter" data-level="6.1.8" data-path="loading-data-1.html"><a href="loading-data-1.html#question-8"><i class="fa fa-check"></i><b>6.1.8</b> Question 8</a></li>
<li class="chapter" data-level="6.1.9" data-path="loading-data-1.html"><a href="loading-data-1.html#question-9"><i class="fa fa-check"></i><b>6.1.9</b> Question 9</a></li>
<li class="chapter" data-level="6.1.10" data-path="loading-data-1.html"><a href="loading-data-1.html#question-10"><i class="fa fa-check"></i><b>6.1.10</b> Question 10</a></li>
<li class="chapter" data-level="6.1.11" data-path="loading-data-1.html"><a href="loading-data-1.html#question-11"><i class="fa fa-check"></i><b>6.1.11</b> Question 11</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="week-3-home.html"><a href="week-3-home.html"><i class="fa fa-check"></i><b>7</b> Week 3 - Home</a><ul>
<li class="chapter" data-level="7.0.1" data-path="week-3-home.html"><a href="week-3-home.html#get-started-with-lavaan"><i class="fa fa-check"></i><b>7.0.1</b> Get started with lavaan</a></li>
<li class="chapter" data-level="7.0.2" data-path="week-3-home.html"><a href="week-3-home.html#regression-models-in-lavaan"><i class="fa fa-check"></i><b>7.0.2</b> Regression models in lavaan</a></li>
<li class="chapter" data-level="7.0.3" data-path="week-3-home.html"><a href="week-3-home.html#conceptual-model"><i class="fa fa-check"></i><b>7.0.3</b> Conceptual model</a></li>
<li class="chapter" data-level="7.0.4" data-path="week-3-home.html"><a href="week-3-home.html#lavaan-syntax"><i class="fa fa-check"></i><b>7.0.4</b> Lavaan syntax</a></li>
<li class="chapter" data-level="7.0.5" data-path="week-3-home.html"><a href="week-3-home.html#performing-the-analysis"><i class="fa fa-check"></i><b>7.0.5</b> Performing the analysis</a></li>
<li class="chapter" data-level="7.0.6" data-path="week-3-home.html"><a href="week-3-home.html#viewing-the-output"><i class="fa fa-check"></i><b>7.0.6</b> Viewing the output</a></li>
<li class="chapter" data-level="7.0.7" data-path="week-3-home.html"><a href="week-3-home.html#plotting-the-output"><i class="fa fa-check"></i><b>7.0.7</b> Plotting the output</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="week-3-class.html"><a href="week-3-class.html"><i class="fa fa-check"></i><b>8</b> Week 3 - Class</a><ul>
<li class="chapter" data-level="8.0.1" data-path="week-3-class.html"><a href="week-3-class.html#question-1-1"><i class="fa fa-check"></i><b>8.0.1</b> Question 1</a></li>
<li class="chapter" data-level="8.0.2" data-path="week-3-class.html"><a href="week-3-class.html#question-2-1"><i class="fa fa-check"></i><b>8.0.2</b> Question 2</a></li>
<li class="chapter" data-level="8.0.3" data-path="week-3-class.html"><a href="week-3-class.html#question-3-1"><i class="fa fa-check"></i><b>8.0.3</b> Question 3</a></li>
<li class="chapter" data-level="8.0.4" data-path="week-3-class.html"><a href="week-3-class.html#question-4-1"><i class="fa fa-check"></i><b>8.0.4</b> Question 4</a></li>
<li class="chapter" data-level="8.0.5" data-path="week-3-class.html"><a href="week-3-class.html#question-5-1"><i class="fa fa-check"></i><b>8.0.5</b> Question 5</a></li>
<li class="chapter" data-level="8.0.6" data-path="week-3-class.html"><a href="week-3-class.html#question-6-1"><i class="fa fa-check"></i><b>8.0.6</b> Question 6</a></li>
<li class="chapter" data-level="8.0.7" data-path="week-3-class.html"><a href="week-3-class.html#question-7-1"><i class="fa fa-check"></i><b>8.0.7</b> Question 7</a></li>
<li class="chapter" data-level="8.0.8" data-path="week-3-class.html"><a href="week-3-class.html#question-8-1"><i class="fa fa-check"></i><b>8.0.8</b> Question 8</a></li>
<li class="chapter" data-level="8.0.9" data-path="week-3-class.html"><a href="week-3-class.html#question-9-1"><i class="fa fa-check"></i><b>8.0.9</b> Question 9</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="week-4-home.html"><a href="week-4-home.html"><i class="fa fa-check"></i><b>9</b> Week 4 - Home</a><ul>
<li class="chapter" data-level="9.0.1" data-path="week-4-home.html"><a href="week-4-home.html#question-1-2"><i class="fa fa-check"></i><b>9.0.1</b> Question 1</a></li>
<li class="chapter" data-level="9.0.2" data-path="week-4-home.html"><a href="week-4-home.html#question-2-2"><i class="fa fa-check"></i><b>9.0.2</b> Question 2</a></li>
<li class="chapter" data-level="9.0.3" data-path="week-4-home.html"><a href="week-4-home.html#question-3-2"><i class="fa fa-check"></i><b>9.0.3</b> Question 3</a></li>
<li class="chapter" data-level="9.0.4" data-path="week-4-home.html"><a href="week-4-home.html#question-4-2"><i class="fa fa-check"></i><b>9.0.4</b> Question 4</a></li>
<li class="chapter" data-level="9.0.5" data-path="week-4-home.html"><a href="week-4-home.html#question-5-2"><i class="fa fa-check"></i><b>9.0.5</b> Question 5</a></li>
<li class="chapter" data-level="9.0.6" data-path="week-4-home.html"><a href="week-4-home.html#question-6-2"><i class="fa fa-check"></i><b>9.0.6</b> Question 6</a></li>
<li class="chapter" data-level="9.0.7" data-path="week-4-home.html"><a href="week-4-home.html#question-7-2"><i class="fa fa-check"></i><b>9.0.7</b> QUestion 7</a></li>
<li class="chapter" data-level="9.0.8" data-path="week-4-home.html"><a href="week-4-home.html#question-8-2"><i class="fa fa-check"></i><b>9.0.8</b> Question 8</a></li>
<li class="chapter" data-level="9.0.9" data-path="week-4-home.html"><a href="week-4-home.html#additional-options"><i class="fa fa-check"></i><b>9.0.9</b> Additional options</a></li>
<li class="chapter" data-level="9.0.10" data-path="week-4-home.html"><a href="week-4-home.html#question-9-2"><i class="fa fa-check"></i><b>9.0.10</b> Question 9</a></li>
<li class="chapter" data-level="9.0.11" data-path="week-4-home.html"><a href="week-4-home.html#question-10-1"><i class="fa fa-check"></i><b>9.0.11</b> Question 10</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="week-4-home-1.html"><a href="week-4-home-1.html"><i class="fa fa-check"></i><b>10</b> Week 4 - Home</a><ul>
<li class="chapter" data-level="10.0.1" data-path="week-4-home-1.html"><a href="week-4-home-1.html#specify-basic-model"><i class="fa fa-check"></i><b>10.0.1</b> Specify basic model</a></li>
<li class="chapter" data-level="10.0.2" data-path="week-4-home-1.html"><a href="week-4-home-1.html#how-to-run-multi-group-model"><i class="fa fa-check"></i><b>10.0.2</b> How to run multi-group model</a></li>
<li class="chapter" data-level="10.0.3" data-path="week-4-home-1.html"><a href="week-4-home-1.html#question-1-3"><i class="fa fa-check"></i><b>10.0.3</b> Question 1</a></li>
<li class="chapter" data-level="10.0.4" data-path="week-4-home-1.html"><a href="week-4-home-1.html#question-2-3"><i class="fa fa-check"></i><b>10.0.4</b> Question 2</a></li>
<li class="chapter" data-level="10.0.5" data-path="week-4-home-1.html"><a href="week-4-home-1.html#question-3-3"><i class="fa fa-check"></i><b>10.0.5</b> Question 3</a></li>
<li class="chapter" data-level="10.0.6" data-path="week-4-home-1.html"><a href="week-4-home-1.html#question-4-3"><i class="fa fa-check"></i><b>10.0.6</b> Question 4</a></li>
<li class="chapter" data-level="10.0.7" data-path="week-4-home-1.html"><a href="week-4-home-1.html#imposing-constraints"><i class="fa fa-check"></i><b>10.0.7</b> Imposing constraints</a></li>
<li class="chapter" data-level="10.0.8" data-path="week-4-home-1.html"><a href="week-4-home-1.html#stepwise-approach"><i class="fa fa-check"></i><b>10.0.8</b> Stepwise approach</a></li>
<li class="chapter" data-level="10.0.9" data-path="week-4-home-1.html"><a href="week-4-home-1.html#question-5-3"><i class="fa fa-check"></i><b>10.0.9</b> Question 5</a></li>
<li class="chapter" data-level="10.0.10" data-path="week-4-home-1.html"><a href="week-4-home-1.html#question-6-3"><i class="fa fa-check"></i><b>10.0.10</b> Question 6</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Theory Construction and Statistical Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="week-4---home" class="section level1">
<h1><span class="header-section-number">Chapter 9</span> Week 4 - Home</h1>
<p>Load the data file SocialRejection.sav into R. It contains three variables: Condition (IV), SelfEst (IV), and Spent (DV).</p>
<div id="question-1-2" class="section level3">
<h3><span class="header-section-number">9.0.1</span> Question 1</h3>
<p>Check the assumption of homogeneous regression lines (no interaction) first. What is your conclusion?</p>
<p><em>Hint: You need to estimate a model with, and one without an interaction, and compare them using the <code>anova()</code> function.</em></p>
<details>
<p><summary>Click for explanation</summary></p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb153-1" data-line-number="1">ancova_main &lt;-<span class="st"> </span><span class="kw">aov</span>(Spent <span class="op">~</span><span class="st"> </span>Condition <span class="op">+</span><span class="st"> </span>SelfEst, <span class="dt">data =</span> data)</a>
<a class="sourceLine" id="cb153-2" data-line-number="2">ancova_int &lt;-<span class="st"> </span><span class="kw">aov</span>(Spent <span class="op">~</span><span class="st"> </span>Condition<span class="op">*</span>SelfEst, <span class="dt">data =</span> data)</a>
<a class="sourceLine" id="cb153-3" data-line-number="3"><span class="kw">anova</span>(ancova_main, ancova_int)</a></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Res.Df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["RSS"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Df"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Sum of Sq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["F"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[6],"type":["dbl"],"align":["right"]}],"data":[{"1":"55","2":"792.3992","3":"NA","4":"NA","5":"NA","6":"NA","_rn_":"1"},{"1":"53","2":"783.7732","3":"2","4":"8.626028","5":"0.2916529","6":"0.7482189","_rn_":"2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>The lines are homogeneous, the assumption is met (interaction is not significant).</p>

</div>
<div id="question-2-2" class="section level3">
<h3><span class="header-section-number">9.0.2</span> Question 2</h3>
<p>What should you do when this assumption is violated?</p>
</div>
<div id="question-3-2" class="section level3">
<h3><span class="header-section-number">9.0.3</span> Question 3</h3>
<p>Before you can do an ANCOVA, you should also check the assumption of homogeneity. What does homogeneity imply, and is the assumption met?</p>
<p><em>Hint: You did this in the Week 1 class exercise.</em></p>
<details>
<p><summary>Click for explanation</summary></p>
<p>We can do a test of homogeneity of the variances of Spent across conditions:</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb154-1" data-line-number="1"><span class="kw">bartlett.test</span>(<span class="dt">formula =</span> Spent<span class="op">~</span>Condition, <span class="dt">data =</span> data)</a></code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  Spent by Condition
## Bartlett&#39;s K-squared = 0.16678, df = 2, p-value = 0.92</code></pre>
<p>However, note that the assumption of homogeneity actually requires the <strong>residual</strong> variance, after controlling for the covariate SelfEst, to be the same across conditions. We can extract these residuals from a regression with only SelfEst as a predictor:</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb156-1" data-line-number="1">reg_selfest &lt;-<span class="st"> </span><span class="kw">lm</span>(Spent <span class="op">~</span><span class="st"> </span>SelfEst, <span class="dt">data =</span> data)</a>
<a class="sourceLine" id="cb156-2" data-line-number="2">residuals_selfest &lt;-<span class="st"> </span>reg_selfest<span class="op">$</span>residuals</a></code></pre></div>
<p>Then, we can test the null hypothesis that the error variance of the dependent variable is equal across groups:</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb157-1" data-line-number="1"><span class="kw">bartlett.test</span>(residuals_selfest, data<span class="op">$</span>Condition)</a></code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  residuals_selfest and data$Condition
## Bartlett&#39;s K-squared = 0.92603, df = 2, p-value = 0.6294</code></pre>
<p>The test is not significant, meaning that the error variances are indeed equal, the assumption is met.</p>

</div>
<div id="question-4-2" class="section level3">
<h3><span class="header-section-number">9.0.4</span> Question 4</h3>
<p>What should you do when this assumption is violated?</p>
<details>
<p><summary>Click for explanation</summary>
You cannot really “solve” this problem in classical regression or ANCOVA, because only one parameter is estimated for the error variance. In SEM, however, you can estimate different error variance parameters for each group.
</p>
</div>
<div id="question-5-2" class="section level3">
<h3><span class="header-section-number">9.0.5</span> Question 5</h3>
<p>Run the actual ANCOVA (or use previous output). What are your conclusions about the effects of the factor and the covariate?</p>
<details>
<p><summary>Click for explanation</summary></p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb159-1" data-line-number="1"><span class="kw">summary</span>(ancova_main)</a></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Condition    2  126.8    63.4   4.402   0.0169 *  
## SelfEst      1  419.5   419.5  29.118 1.49e-06 ***
## Residuals   55  792.4    14.4                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Self esteem is significant, F (1, 55) = 29.118, p &lt; .001, the level of self esteem of the respondent is related to the amount spent.
Condition is significant after controlling for the effect of self-esteem, F (2, 55) = 4.402, p = .017, the amount spent differs between the three conditions.</p>

</div>
<div id="question-6-2" class="section level3">
<h3><span class="header-section-number">9.0.6</span> Question 6</h3>
<p>Let’s examine the differences in conditional means between the three conditions. In order to do so, we can use several approaches.</p>
<div id="approach-1-conditional-means" class="section level4">
<h4><span class="header-section-number">9.0.6.1</span> Approach 1: Conditional means</h4>
<p>We can obtain the conditional means of the three groups by asking for the predicted (expected) value, based on the model, for each of the three conditions, keeping the covariate constant at 0. For this, we apply the <code>predict()</code> function to the object containing our analysis. We make a small new dataset for the values that we want predictions for:</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb161-1" data-line-number="1">new_data &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Condition =</span> <span class="kw">c</span>(<span class="st">&quot;rejection&quot;</span>, <span class="st">&quot;neutral&quot;</span>, <span class="st">&quot;confirming&quot;</span>), </a>
<a class="sourceLine" id="cb161-2" data-line-number="2">                       <span class="dt">SelfEst =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>))</a>
<a class="sourceLine" id="cb161-3" data-line-number="3"><span class="kw">predict</span>(ancova_main, new_data)</a></code></pre></div>
<pre><code>##         1         2         3 
## 12.449100 10.265532  9.152918</code></pre>
<p>What are your conclusions about the three conditions (i.e., how do they differ)?</p>
</div>
<div id="approach-2-testing-significance" class="section level4">
<h4><span class="header-section-number">9.0.6.2</span> Approach 2: Testing significance</h4>
<p>We can test the significance for these differences using <code>TukeyHSD()</code> again, but to get the conditional means, we need to use the residuals from a model that includes only SelfEst, which we obtained before:</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb163-1" data-line-number="1">reg_selfest &lt;-<span class="st"> </span><span class="kw">lm</span>(Spent <span class="op">~</span><span class="st"> </span>SelfEst, <span class="dt">data =</span> data)</a>
<a class="sourceLine" id="cb163-2" data-line-number="2">residuals_selfest &lt;-<span class="st"> </span>reg_selfest<span class="op">$</span>residuals</a>
<a class="sourceLine" id="cb163-3" data-line-number="3">anova_conditional &lt;-<span class="st"> </span><span class="kw">aov</span>(residuals_selfest <span class="op">~</span><span class="st"> </span>data<span class="op">$</span>Condition)</a>
<a class="sourceLine" id="cb163-4" data-line-number="4"><span class="kw">TukeyHSD</span>(anova_conditional)</a></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = residuals_selfest ~ data$Condition)
## 
## $`data$Condition`
##                           diff       lwr        upr     p adj
## neutral-rejection    -2.174775 -5.076198  0.7266467 0.1773921
## confirming-rejection -3.296276 -6.197698 -0.3948536 0.0223500
## confirming-neutral   -1.121500 -3.985483  1.7424826 0.6157693</code></pre>
<p>Respondents in the rejection condition spent more, than respondents in the neutral condition and the confirming condition. These differences are not tested on significance between two groups.</p>
</div>
<div id="approach-3-plotting-the-difference" class="section level4">
<h4><span class="header-section-number">9.0.6.3</span> Approach 3: Plotting the difference</h4>
<p>This is where R really shines: We can quickly put together a plot that shows the difference between groups, along with the raw data. We use the package <code>ggplot2</code></p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb165-1" data-line-number="1"><span class="kw">library</span>(ggplot2)</a>
<a class="sourceLine" id="cb165-2" data-line-number="2"><span class="co"># Put the data for the plot together</span></a>
<a class="sourceLine" id="cb165-3" data-line-number="3">plot_data &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Spent_resid =</span> residuals_selfest,</a>
<a class="sourceLine" id="cb165-4" data-line-number="4">                        <span class="dt">Condition =</span> data<span class="op">$</span>Condition)</a>
<a class="sourceLine" id="cb165-5" data-line-number="5"><span class="co"># Basic plot; indicate that you want condition on the x-axis and Spent_resid on</span></a>
<a class="sourceLine" id="cb165-6" data-line-number="6"><span class="co"># the y-axis</span></a>
<a class="sourceLine" id="cb165-7" data-line-number="7"><span class="kw">ggplot</span>(plot_data, <span class="kw">aes</span>(<span class="dt">x =</span> Condition, <span class="dt">y =</span> Spent_resid)) <span class="op">+</span></a>
<a class="sourceLine" id="cb165-8" data-line-number="8"><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span><span class="co"># Add a boxplot for each condition</span></a>
<a class="sourceLine" id="cb165-9" data-line-number="9"><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">width =</span> <span class="fl">.2</span>) <span class="op">+</span><span class="st"> </span><span class="co"># Plot raw datapoints on top</span></a>
<a class="sourceLine" id="cb165-10" data-line-number="10"><span class="st">  </span><span class="kw">theme_bw</span>() <span class="co"># Add a nice APA theme</span></a></code></pre></div>
<p><img src="TCSM_files/figure-html/unnamed-chunk-127-1.png" width="672" /></p>
</div>
</div>
<div id="question-7-2" class="section level3">
<h3><span class="header-section-number">9.0.7</span> QUestion 7</h3>
<p>An AN(C)OVA can also be specified as a regression analysis. R automatically creates dummies. Use the <code>lm()</code> function instead of <code>aov()</code>, and compare the results.</p>
<details>
<p><summary>Click for explanation</summary></p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb166-1" data-line-number="1">ancova_main &lt;-<span class="st"> </span><span class="kw">aov</span>(Spent <span class="op">~</span><span class="st"> </span>Condition <span class="op">+</span><span class="st"> </span>SelfEst, <span class="dt">data =</span> data)</a>
<a class="sourceLine" id="cb166-2" data-line-number="2"><span class="kw">summary</span>(ancova_main)</a></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Condition    2  126.8    63.4   4.402   0.0169 *  
## SelfEst      1  419.5   419.5  29.118 1.49e-06 ***
## Residuals   55  792.4    14.4                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb168-1" data-line-number="1">lm_main &lt;-<span class="st"> </span><span class="kw">lm</span>(Spent <span class="op">~</span><span class="st"> </span>Condition <span class="op">+</span><span class="st"> </span>SelfEst, <span class="dt">data =</span> data)</a>
<a class="sourceLine" id="cb168-2" data-line-number="2"><span class="kw">summary</span>(lm_main)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Spent ~ Condition + SelfEst, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.9987 -2.5886 -0.4841  1.9772 10.6503 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         12.44910    1.98050   6.286 5.54e-08 ***
## Conditionneutral    -2.18357    1.22451  -1.783  0.08007 .  
## Conditionconfirming -3.29618    1.21599  -2.711  0.00894 ** 
## SelfEst             -0.52406    0.09712  -5.396 1.49e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.796 on 55 degrees of freedom
## Multiple R-squared:  0.4081, Adjusted R-squared:  0.3758 
## F-statistic: 12.64 on 3 and 55 DF,  p-value: 2.142e-06</code></pre>

<p>You can get the conditional means directly from this <code>lm()</code> model by dropping the intercept, using <code>-1</code> (which means: minus the intercept) in the formula:</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb170-1" data-line-number="1">lm_no_intercept &lt;-<span class="st"> </span><span class="kw">lm</span>(Spent <span class="op">~</span><span class="st"> </span><span class="dv">-1</span> <span class="op">+</span><span class="st"> </span>Condition <span class="op">+</span><span class="st"> </span>SelfEst, <span class="dt">data =</span> data)</a>
<a class="sourceLine" id="cb170-2" data-line-number="2"><span class="kw">summary</span>(lm_no_intercept)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Spent ~ -1 + Condition + SelfEst, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.9987 -2.5886 -0.4841  1.9772 10.6503 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## Conditionrejection  12.44910    1.98050   6.286 5.54e-08 ***
## Conditionneutral    10.26553    2.10191   4.884 9.35e-06 ***
## Conditionconfirming  9.15292    1.96952   4.647 2.14e-05 ***
## SelfEst             -0.52406    0.09712  -5.396 1.49e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.796 on 55 degrees of freedom
## Multiple R-squared:  0.4218, Adjusted R-squared:  0.3797 
## F-statistic: 10.03 on 4 and 55 DF,  p-value: 3.616e-06</code></pre>
</div>
<div id="question-8-2" class="section level3">
<h3><span class="header-section-number">9.0.8</span> Question 8</h3>
<p>To perform this analysis as a structural equation model, we need to manually compute dummy variables. We can use the function <code>model.matrix()</code> to “expand” a factor variable into dummies:</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb172-1" data-line-number="1">data_dummies &lt;-<span class="st"> </span><span class="kw">model.matrix</span>(<span class="op">~</span><span class="st"> </span><span class="dv">-1</span> <span class="op">+</span><span class="st"> </span>Condition, <span class="dt">data =</span> data)</a>
<a class="sourceLine" id="cb172-2" data-line-number="2"><span class="kw">head</span>(data_dummies)</a></code></pre></div>
<pre><code>##   Conditionrejection Conditionneutral Conditionconfirming
## 1                  1                0                   0
## 2                  1                0                   0
## 3                  1                0                   0
## 4                  1                0                   0
## 5                  1                0                   0
## 6                  1                0                   0</code></pre>
<p>We can then bind these columns with dummies to our original data using <code>cbind()</code> (column bind):</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb174-1" data-line-number="1">data &lt;-<span class="st"> </span><span class="kw">cbind</span>(data, data_dummies)</a>
<a class="sourceLine" id="cb174-2" data-line-number="2"><span class="kw">head</span>(data)</a></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Condition"],"name":[1],"type":["fctr"],"align":["left"]},{"label":["SelfEst"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Spent"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Conditionrejection"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Conditionneutral"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["Conditionconfirming"],"name":[6],"type":["dbl"],"align":["right"]}],"data":[{"1":"rejection","2":"10","3":"4.785362","4":"1","5":"0","6":"0","_rn_":"1"},{"1":"rejection","2":"18","3":"4.434689","4":"1","5":"0","6":"0","_rn_":"2"},{"1":"rejection","2":"10","3":"6.323272","4":"1","5":"0","6":"0","_rn_":"3"},{"1":"rejection","2":"11","3":"4.823320","4":"1","5":"0","6":"0","_rn_":"4"},{"1":"rejection","2":"22","3":"6.449067","4":"1","5":"0","6":"0","_rn_":"5"},{"1":"rejection","2":"24","3":"4.326671","4":"1","5":"0","6":"0","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Begin by specifying the model in lavaan like this:</p>
<p><img src="week4home1.png" /></p>
<details>
<p><summary>Click for explanation</summary></p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb175-1" data-line-number="1"><span class="kw">library</span>(lavaan)</a>
<a class="sourceLine" id="cb175-2" data-line-number="2">ancova_lavaan &lt;-<span class="st"> </span><span class="kw">sem</span>(<span class="st">&#39;Spent ~ SelfEst + Conditionrejection + Conditionconfirming&#39;</span>, <span class="dt">data =</span> data)</a>
<a class="sourceLine" id="cb175-3" data-line-number="3"><span class="kw">summary</span>(ancova_lavaan)</a></code></pre></div>
<pre><code>## lavaan 0.6-3 ended normally after 21 iterations
## 
##   Optimization method                           NLMINB
##   Number of free parameters                          4
## 
##   Number of observations                            59
## 
##   Estimator                                         ML
##   Model Fit Test Statistic                       0.000
##   Degrees of freedom                                 0
##   Minimum Function Value               0.0000000000000
## 
## Parameter Estimates:
## 
##   Information                                 Expected
##   Information saturated (h1) model          Structured
##   Standard Errors                             Standard
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   Spent ~                                             
##     SelfEst          -0.524    0.094   -5.589    0.000
##     Conditionrjctn    2.184    1.182    1.847    0.065
##     Conditncnfrmng   -1.113    1.167   -0.953    0.341
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Spent            13.430    2.473    5.431    0.000</code></pre>
<p>To obtain a plot of these results and compare it to our picture above, use <code>SemPlot</code>:</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb177-1" data-line-number="1"><span class="kw">library</span>(semPlot)</a>
<a class="sourceLine" id="cb177-2" data-line-number="2"><span class="kw">semPaths</span>(ancova_lavaan, <span class="dt">whatLabels =</span> <span class="st">&quot;est&quot;</span>, <span class="dt">rotation =</span> <span class="dv">2</span>)</a></code></pre></div>
<p><img src="TCSM_files/figure-html/unnamed-chunk-133-1.png" width="672" />
</p>
</div>
<div id="additional-options" class="section level3">
<h3><span class="header-section-number">9.0.9</span> Additional options</h3>
<p><strong>Note:</strong> When you are doing an ANCOVA (even as a regression model with dummies), you want to analyze both the covariance structure AND the mean structure. To include the latter in your analysis, you have to tell lavaan to include this by adding the argument <code>meanstructure = TRUE</code> in the fitting function:</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb178-1" data-line-number="1"><span class="kw">library</span>(lavaan)</a>
<a class="sourceLine" id="cb178-2" data-line-number="2">ancova_lavaan &lt;-<span class="st"> </span><span class="kw">sem</span>(<span class="st">&#39;Spent ~ SelfEst + Conditionrejection + Conditionconfirming&#39;</span>, </a>
<a class="sourceLine" id="cb178-3" data-line-number="3">                     <span class="dt">data =</span> data,</a>
<a class="sourceLine" id="cb178-4" data-line-number="4">                     <span class="dt">meanstructure =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb178-5" data-line-number="5"><span class="kw">summary</span>(ancova_lavaan)</a></code></pre></div>
<pre><code>## lavaan 0.6-3 ended normally after 35 iterations
## 
##   Optimization method                           NLMINB
##   Number of free parameters                          5
## 
##   Number of observations                            59
## 
##   Estimator                                         ML
##   Model Fit Test Statistic                       0.000
##   Degrees of freedom                                 0
## 
## Parameter Estimates:
## 
##   Information                                 Expected
##   Information saturated (h1) model          Structured
##   Standard Errors                             Standard
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   Spent ~                                             
##     SelfEst          -0.524    0.094   -5.589    0.000
##     Conditionrjctn    2.184    1.182    1.847    0.065
##     Conditncnfrmng   -1.113    1.167   -0.953    0.341
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Spent            10.266    2.029    5.058    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Spent            13.430    2.473    5.431    0.000</code></pre>
<p>To obtain the standardized results and the proportion of explained variance (= squared multiple correlation, i.e., R2), you can use the options in the <code>summary()</code> function:</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb180-1" data-line-number="1"><span class="kw">summary</span>(ancova_lavaan, <span class="dt">standardized =</span> <span class="ot">TRUE</span>, <span class="dt">rsquare =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## lavaan 0.6-3 ended normally after 35 iterations
## 
##   Optimization method                           NLMINB
##   Number of free parameters                          5
## 
##   Number of observations                            59
## 
##   Estimator                                         ML
##   Model Fit Test Statistic                       0.000
##   Degrees of freedom                                 0
## 
## Parameter Estimates:
## 
##   Information                                 Expected
##   Information saturated (h1) model          Structured
##   Standard Errors                             Standard
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   Spent ~                                                               
##     SelfEst          -0.524    0.094   -5.589    0.000   -0.524   -0.565
##     Conditionrjctn    2.184    1.182    1.847    0.065    2.184    0.214
##     Conditncnfrmng   -1.113    1.167   -0.953    0.341   -1.113   -0.111
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .Spent            10.266    2.029    5.058    0.000   10.266    2.155
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .Spent            13.430    2.473    5.431    0.000   13.430    0.592
## 
## R-Square:
##                    Estimate
##     Spent             0.408</code></pre>
</div>
<div id="question-9-2" class="section level3">
<h3><span class="header-section-number">9.0.10</span> Question 9</h3>
<p>Compare your results to those obtained with the regression analysis. What is your conclusion?</p>
</div>
<div id="question-10-1" class="section level3">
<h3><span class="header-section-number">9.0.11</span> Question 10</h3>
<p>Check the model fit. What do you conclude?</p>
<p><em>Note: Use</em> <code>summary()</code> <em>and</em> <code>fit.measures = TRUE</code></p>
<details>
<p><summary>Click for explanation</summary></p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb182-1" data-line-number="1"><span class="kw">summary</span>(ancova_lavaan, <span class="dt">fit.measures =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## lavaan 0.6-3 ended normally after 35 iterations
## 
##   Optimization method                           NLMINB
##   Number of free parameters                          5
## 
##   Number of observations                            59
## 
##   Estimator                                         ML
##   Model Fit Test Statistic                       0.000
##   Degrees of freedom                                 0
## 
## Model test baseline model:
## 
##   Minimum Function Test Statistic               30.941
##   Degrees of freedom                                 3
##   P-value                                        0.000
## 
## User model versus baseline model:
## 
##   Comparative Fit Index (CFI)                    1.000
##   Tucker-Lewis Index (TLI)                       1.000
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)               -160.344
##   Loglikelihood unrestricted model (H1)       -160.344
## 
##   Number of free parameters                          5
##   Akaike (AIC)                                 330.689
##   Bayesian (BIC)                               341.077
##   Sample-size adjusted Bayesian (BIC)          325.353
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.000
##   90 Percent Confidence Interval          0.000  0.000
##   P-value RMSEA &lt;= 0.05                             NA
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.000
## 
## Parameter Estimates:
## 
##   Information                                 Expected
##   Information saturated (h1) model          Structured
##   Standard Errors                             Standard
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   Spent ~                                             
##     SelfEst          -0.524    0.094   -5.589    0.000
##     Conditionrjctn    2.184    1.182    1.847    0.065
##     Conditncnfrmng   -1.113    1.167   -0.953    0.341
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Spent            10.266    2.029    5.058    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Spent            13.430    2.473    5.431    0.000</code></pre>
<p>Saturated model, so perfect fit. Because the number of parameters to be estimated is equal to the number of observed statistics, there is a perfect fit. Here our interest is mainly in getting the estimates, not in the model-fit.
</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="week-3-class.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="week-4-home-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["TCSM.pdf"],
"toc": {
"collapse": "section"
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
